import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <h1>🤏 Smol URL</h1>
       <h3>Enter a long URL to make a SmolURL:</h3>
       <form>
  <label>
    Long URL:
    <input type="text" name="name" />
  </label>
  <input type="submit" value="Submit" />
  </form>
      </main>
    </>
  )
}
